
// This file has been generated by the GUI designer. Do not modify.
namespace ServiceStackXS
{
	public partial class SettingsWidget
	{
		private global::Gtk.Fixed fixed2;

		private global::Gtk.CheckButton optOutCheckbox;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ServiceStackXS.SettingsWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "ServiceStackXS.SettingsWidget";
			// Container child ServiceStackXS.SettingsWidget.Gtk.Container+ContainerChild
			this.fixed2 = new global::Gtk.Fixed();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.optOutCheckbox = new global::Gtk.CheckButton();
			this.optOutCheckbox.CanFocus = true;
			this.optOutCheckbox.Name = "optOutCheckbox";
			this.optOutCheckbox.Label = global::Mono.Unix.Catalog.GetString("Opt out of anonymous usage statistics");
			this.optOutCheckbox.DrawIndicator = true;
			this.optOutCheckbox.UseUnderline = true;
			this.fixed2.Add(this.optOutCheckbox);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.optOutCheckbox]));
			w1.X = 10;
			w1.Y = 17;
			this.Add(this.fixed2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
